### ISSUE TITLE
Unable to import module

### ISSUE THREAD

**Issue by Windos** [pcgeek86/PSPuTTY#2]
Realise that this is still WIP, but figured I'd open an issue for this one regardless:

Importing the module fails due to two things in the .psm1 file:
1. The `using module PSPuTTY-Models`
2. Running Get-ChildItem against the non-existent (in the remote version of this at any rate) aliases directory.

Commenting out those on my local machine allows the module to import successfully. If it affects anything, I installed from the gallery.

p,s, as a daily user of PuTTY, the idea behind this module is really awesome to me and I can't wait to see it take shape. If I can be of any assistance building this out, let me know. Happy to help.

**Comment by pcgeek86** [comment]
@Windos sorry about that -- yeah that was a known bug. It should be fixed in a more recent commit.
